name: Build after Push

on:
  push:
    branches:
      - master  
  workflow_dispatch:  
    inputs:
      build_type:
        description: "Tipo di build (esempio: fast-build, full-build)"
        required: true
        default: "fast-build"

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install --force

      - name: Build App
        run: npx nx build documentation-app